### ISSUE TITLE
Provide the XSD of the jQAssistant Rules file online

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqassistant#202]
The manual uses the URL `http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0` to refer to the XSD of the rules XML. Unfortunately the XSD is not available at this URL. It would be usefull to have it online to be able to download it. For example Intellij IDEA allows you to fetch an XSD from its URL. Afterwards it is able to use it for the XML files using this XSD.

**Comment by ronanquillevere** [comment]
+1

http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0

-> 404 error

**Comment by ronanquillevere** [comment]
For information,

http://raw.githubusercontent.com/buschmais/jqassistant/master/core/analysis/src/main/resources/META-INF/xsd/jqassistant-rules-1.0.xsd

**Comment by clemensbartz** [comment]
Link to the 1.0 version with commit hash:
https://raw.githubusercontent.com/jQAssistant/jqa-core-framework/b688dbf42d274881312a1e2fd1370d97224f7c38/analysis/src/main/resources/META-INF/xsd/jqassistant-rules-1.0.xsd

**Comment by DirkMahler** [comment]
The issue will be fixed with 1.8, see https://github.com/jQAssistant/jqa-core-framework/issues/32.
