### ISSUE TITLE
Publish generated docs as part of release build

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqassistant#471]
The Maven build creates a zip file containing the manual which is committed to the gh-pages branch as a manual step. 

It needs to be clarified if we want to keep the GH pages approach, in this case the upload should happen automatically during a release build.

Another option would be that the docs are just adoc files beside the source code that are rendered by GitHub. In this case we need to define how to deal with generated docs (i.e. plugin rules)

**Comment by DirkMahler** [comment]
If possible there should be different paths used in the URL for CI and release workflow:

* CI workflow : "/snapshot"
* Release workflow: "/release"

**Comment by yaseno2186** [comment]
last commit is wrong , does nothing with this ticket
